### ISSUE TITLE
Actualizar Versión en pypi

### ISSUE THREAD

**Issue by dansanti** [fixmycode/pykhipu#2]
hola!

es posible de que porfavor hagan el incremento de la versión, lo empaqueten y suban a pypi?

**Comment by fixmycode** [comment]
por supuesto, juraba que lo había empaquetado cuando @cfdroguettr parchó esos temas pero se me olvidó

**Comment by dansanti** [comment]
deben incrmentar a 0.1.5 o pypi no les dejará subir

**Comment by fixmycode** [comment]
nueva versión publicada, el proceso quedó automatizado para que se realice cada vez que publique un release
