### ISSUE TITLE
Variables no definidas en clase PaymentsCreateResponse

### ISSUE THREAD

**Issue by celm1990** [fixmycode/pykhipu#4]
Estimados estoy probando la libreria pero obtengo el siguiente error.
estoy probando sobre ubuntu 18.04 y python 3.6

![image](https://user-images.githubusercontent.com/7775116/91932224-2a368400-ecab-11ea-8765-cbd48e7b76d9.png)

el error se da en estas lineas
https://github.com/fixmycode/pykhipu/blob/master/pykhipu/responses.py#L410-L412

la llamada viene desde aca https://github.com/fixmycode/pykhipu/blob/master/pykhipu/payments.py#L39

Error introducido en el commit https://github.com/fixmycode/pykhipu/commit/bb7deb9615d269ad59a4e70de3f66643ccced430

**Comment by fixmycode** [comment]
reparado en a5a15de, el parche ya ha sido publicado en Pypi con la versión 0.1.7

**Comment by celm1990** [comment]
muchas gracias por la pronta respuesta, temporalmente habia instalado la version 0.1.5 que no tenia ese problema. Actualizare la ultima version
