### ISSUE TITLE
Problemas al solicitar estado del pago

### ISSUE THREAD

**Issue by tsepulvedacaroca01** [fixmycode/pykhipu#5]
Hola,

Primero que nada, gracias por compartir esta librería, pero al parecer me he encontrado con un problema al momento de consultar el estado del pago (adjunto el error).

web_1  |   File "/usr/local/lib/python3.6/site-packages/pykhipu/payments.py", line 48, in get_id
web_1  |     return PaymentsResponse.from_response(response)
web_1  |   File "/usr/local/lib/python3.6/site-packages/pykhipu/responses.py", line 14, in from_response
web_1  |     return cls.from_data(data)
web_1  |   File "/usr/local/lib/python3.6/site-packages/pykhipu/responses.py", line 77, in from_data
web_1  |     conciliation_date = dateutil.parser.parse(data.get('conciliation_date'))
web_1  |   File "/usr/local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
web_1  |     return DEFAULTPARSER.parse(timestr, **kwargs)
web_1  |   File "/usr/local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 646, in parse
web_1  |     res, skipped_tokens = self._parse(timestr, **kwargs)
web_1  |   File "/usr/local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 725, in _parse
web_1  |     l = _timelex.split(timestr)         # Splits the timestr into tokens
web_1  |   File "/usr/local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 207, in split
web_1  |     return list(cls(s))
web_1  |   File "/usr/local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 76, in __init__
web_1  |     '{itype}'.format(itype=instream.__class__.__name__))
web_1  | TypeError: Parser must be a string or character stream, not NoneType

Para entrar en detalles, consulté un pago que aún se encuentra en proceso y arroja el error presentado. Luego consulté un pago que ya fue realizado y funciona perfectamente. Estuve realizando el seguimiento a las respuestas y al código y al parecer no retorna la misma cantidad de llaves al momento de realizar el GET cuando el pago se encuentra o no pagado.

Versión utilizada: 0.1.7

**Comment by fixmycode** [comment]
debería quedar solucionado con el parche 254693b10d6a895fcde224ebfbe659869366b536
ya está publicado en PyPI con la versión v0.1.8

**Comment by tsepulvedacaroca01** [comment]
Gracias por la pronta respuesta y su correspondiente solución.

**Comment by fixmycode** [comment]
gracias por tu retroalimentación
